#ifndef _WINGCONFIG_H__
#define _WINGCONFIG_H__



//#define WIRELESS_DEBUGGING

#define ATTITUDE_CONTROL
#define ALTITUDE_CONTROL
#define SERIAL_COMUNICATION

#define TIMED_MULTIPLEX_CONTROL
#define TIMED_MULTIPLEX_CONTROL_DELAY_COUNT 4



#endif